# Uncomment the next line to define a global platform for your project
platform :ios, ’10.0’

target 'VSVerticalSliderSample' do

  use_frameworks!
  pod 'VSVerticalSlider', :git => 'https://github.com/vsmithers1087/VSVerticalSlider.git'

end
